spring.application.name=CompSysten

spring.datasource.url=jdbc:mysql://localhost:3306/complaint_tracker
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.servlet.session.cookie.http-only=false
server.servlet.session.cookie.same-site=lax
server.servlet.session.timeout=30m